language: R
script: make

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master

# matrix:
#   include:
#     - os: linux
#       addons:
#         apt:
#           sources: ubuntu-toolchain-r-test
#           packages:
#             - g++-8
#             - cppcheck
#             - sloccount
