language: R
install:
  - R -e "install.packages('rjson')"
  - R -e "install.packages('rmarkdown')"

script: make

deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master
