language: R
install:
  - R -e "install.packages('rjson')"
  - R -e "install.packages('rmarkdown')"
  - R -e "install.packages('pracma')"

script: make && mv .gitignore tmp/

deploy:
  provider: pages
  github-token: ${github_token}
  skip-cleanup: true
  on:
    branch: master
