---
title: tradeR
date: "Last update: `r Sys.time()` in `r Sys.timezone()`"
output:
  html_document:
    df_print: kable
    code_folding: "hide"
    theme: united
    highlight: zenburn
---

```{r, read and extract}
# Read JSON files and extract the prices
library("rjson")

# Read any files on disk
files <- list.files(path = "tmp", pattern = "*.json", full.names = TRUE)
stopifnot(length(files) > 0)

# Extract the interesting bits
extract <- function(f){
      json <- fromJSON(file = f)
      if (length(json))
        sapply(json$Data, function(x) { mean(c(x$open, x$high, x$low)) })
}

# Extract all series
prices <-as.data.frame(sapply(files, extract))

# Add a random series
random_prices <- cumsum(rnorm(nrow(prices)))
random_prices <- random_prices + 8000
prices <- cbind(TURBO = random_prices, prices)
```

# Analysis
```{r, analysis}
buy_now <- function(s) {
  tail(s, 1) < (mean(s) - (2 * sd(s)))
}

# Plot prices and ilnear regression
linear_regression <- function(name) {

  # Get prices for token
  y <- unlist(prices[name])
  x <- seq(length(y))

  # Trading advice
  # Report if latest value exceeds mean by standard deviation
  standard_deviation <- sd(y)
  advice <- "stable"

  if (tail(y, 1) > mean(y) + standard_deviation)
    advice <- "UP!"
  else if (tail(y, 1) < mean(y) - standard_deviation)
    advice <- "DOWN!"

  # Create plot titles
  token <- sub("tmp/", "", sub(".json", "", name))
  main_title <- paste(token, advice)
  sub_title <- paste("sd", standard_deviation)

  # Fit line
  relation <- lm(y ~ x)

  # Plot with calculated line
  scatter.smooth(y, type = "l", col = "grey", main = main_title, sub = sub_title,
    xlab = "minutes", ylab = "USD",
    lpars = list(col = "green", lwd = 3, lty = 3))

  # Add linear regression
  abline(relation, col = "orange")
  grid(10, 10)

  trade_window_size <- 80
  r <- c(); for (i in seq(length(y)))
    r <- c(r, NA)

  for (i in seq(length(y) - trade_window_size)) {
    trade_window <- y[i:(i+trade_window_size)]
    if (buy_now(trade_window))
      r[i + trade_window_size] = y[i + trade_window_size]
  }

  points(r, col = "red")

  # Histogram of diffs
  # hist(unlist(y), breaks=500, main = paste("plateaux", token),
  #   sub = paste("std dev", standard_deviation))
}

plots <- sapply(colnames(prices), linear_regression)
```


```{bash, revision info}
git log --oneline -n 1
```
